### ISSUE TITLE
OnlyNew with yearFilter doesn't properly work

### ISSUE THREAD

**Issue by Disane87** [Disane87/docudigger#1140]
Hello!

It seems that on dev.13 the docker image is working again! Great work!

I wanted it to have a full run going, but for some reasons, it does not properly start processing?

Here is the log output:

```
[+] Running 1/0
 ✔ Container amazon-docudigger-1  Created                                                                                      0.0s
Attaching to docudigger-1
docudigger-1  | [0] (node:15) Warning: SyntaxError
docudigger-1  | [0] module: @oclif/core@4.0.31
docudigger-1  | [0] task: findCommand (scrape:all.d)
docudigger-1  | [0] plugin: @disane-dev/docudigger
docudigger-1  | [0] root: /home/node/.npm-global/lib/node_modules/@disane-dev/docudigger
docudigger-1  | [0] message: Cannot use import statement outside a module
docudigger-1  | [0] See more details with DEBUG=*
docudigger-1  | [0] (Use `node --trace-warnings ...` to show where the warning was created)
docudigger-1  | [0] (node:15) Warning: SyntaxError
docudigger-1  | [0] module: @oclif/core@4.0.31
docudigger-1  | [0] task: findCommand (scrape:amazon:index.d)
docudigger-1  | [0] plugin: @disane-dev/docudigger
docudigger-1  | [0] root: /home/node/.npm-global/lib/node_modules/@disane-dev/docudigger
docudigger-1  | [0] message: Cannot use import statement outside a module
docudigger-1  | [0] See more details with DEBUG=*
docudigger-1  | [0] [info] [2024-10-31 10:10:24] [scrape:all]:  runAll
docudigger-1  | [0] Platform:  linux
docudigger-1  | [0] [info] [2024-10-31 10:10:24] [scrape:amazon]:       OnlyNew activated.
docudigger-1  | [0] [info] [2024-10-31 10:10:24] [scrape:amazon]:       Getting last run
docudigger-1  | [0] [warn] [2024-10-31 10:10:24] [scrape:amazon]:       process.json not found. Full run needed. OnlyNew deactivated.
docudigger-1  | [0] [info] [2024-10-31 10:10:24] [scrape:amazon]:       Getting last run. Got: undefined
docudigger-1  | [0] [info] [2024-10-31 10:10:24] [scrape:amazon]:       No latest scrape found. Processing all years and pages.
docudigger-1  | [0] [info] [2024-10-31 10:10:29] [scrape:amazon]:       Logged in
docudigger-1  | [0] [info] [2024-10-31 10:10:32] [scrape:amazon]:       Year filter undefined. Getting all possible years
docudigger-1  | [0] [info] [2024-10-31 10:10:32] [scrape:amazon]:       First possible year: undefined
docudigger-1  | [0] [info] [2024-10-31 10:10:32] [scrape:amazon]:       Last possible year: undefined
docudigger-1  | [0] [info] [2024-10-31 10:10:32] [scrape:amazon]:       Processing years
docudigger-1  | [0] [info] [2024-10-31 10:10:33] [scrape:amazon]:       Recurring activated. Not terminating. Waiting for next run.
docudigger-1  | [0] docudigger scrape all exited with code 0
docudigger-1 exited with code 0
```

Here is the docker file:

```
name: amazon
services:
    docudigger:
        environment:
            - AMAZON_USERNAME=XXXX
            - AMAZON_PASSWORD=XXXX
            - AMAZON_TLD=de
            - AMAZON_YEAR_FILTER=2024
            - AMAZON_PAGE_FILTER=1
        volumes:
            - C:/Users/XXXX/test:/home/node/docudigger
        image: ghcr.io/disane87/docudigger:2.0.6-dev.13
volumes:
    C:
        external: true
        name: C
```

It strange because I do have a year filter active.

_Originally posted by @maxkostas in https://github.com/Disane87/docudigger/issues/1136#issuecomment-2449529760_
